## NumPy Slicing

[start: end]
[start:end:step]

In [4]:
# slice elements from index 1 to 5

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:5])

[2 3 4 5]


In [5]:
# print start to end

import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr[0:])

[1 2 3 4 5 6 7 8 9]


In [8]:
# negative slicing

import numpy as np

arr= np.array([1,2,3,4,5,6,7,8,9])

print(arr[-4:-1])
print(arr[-7:-1])

[6 7 8]
[3 4 5 6 7 8]


In [10]:
# step

import numpy as np

arr= np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:6:2])

[2 4 6]


In [13]:
# return every other elemet from the array

import numpy as np

arr= np.array([1,2,3,4,5,6,7,8,9])

print(arr[0: :2])
print(arr[0: :3])


[1 3 5 7 9]
[1 4 7]


In [21]:
# Slicing 2 d array

#From the second element, slice elements from index 1 to index 5 
#From both elements, return index 3
#From both elements, slice index 1 to index 5, this will return a 2-D array

import numpy as np

arr=np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])

print(arr[1,1:5])  # ( first dimension  and second are elements)
print(arr[0:2,3])
print(arr[0:2,1:5])
print(arr.ndim)

[11 12 13 14]
[ 4 13]
[[ 2  3  4  5]
 [11 12 13 14]]
2
